In [1]:
import numpy as np

scores = np.random.randint(50, 101, size=(5, 3))
mean_scores = scores.mean(axis=0)
centered_scores = scores - mean_scores

print(scores)
print(mean_scores)
print(centered_scores)


[[87 81 68]
 [78 66 88]
 [83 76 97]
 [66 98 70]
 [55 67 83]]
[73.8 77.6 81.2]
[[ 13.2   3.4 -13.2]
 [  4.2 -11.6   6.8]
 [  9.2  -1.6  15.8]
 [ -7.8  20.4 -11.2]
 [-18.8 -10.6   1.8]]


In [2]:
import numpy as np

arr = np.arange(24)
reshaped = arr.reshape(4, 3, 2)
transposed = reshaped.transpose(0, 2, 1)

print(transposed.shape)
print(transposed)


(4, 2, 3)
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
