In [5]:
import numpy as np

np.random.seed(0)
scores = np.random.randint(50, 101, size=(5, 3))
subject_means = scores.mean(axis=0)
centered_scores = scores - subject_means

print("Original Scores:")
print(scores)
print("\nMean")
print(subject_means)
print("\nCentered Scores:")
print(centered_scores)

Original Scores:
[[ 94  97  50]
 [ 53  53  89]
 [ 59  69  71]
 [100  86  73]
 [ 56  74  74]]

Mean
[72.4 75.8 71.4]

Centered Scores:
[[ 21.6  21.2 -21.4]
 [-19.4 -22.8  17.6]
 [-13.4  -6.8  -0.4]
 [ 27.6  10.2   1.6]
 [-16.4  -1.8   2.6]]


In [6]:
import numpy as np

data = np.arange(24)
reshaped_data = data.reshape(4, 3, 2)
final_array = reshaped_data.transpose(0, 2, 1)
final_shape = final_array.shape

print("final_shape")
print(final_shape)
print("final_array")
print(final_array)


final_shape
(4, 2, 3)
final_array
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
